### ISSUE TITLE
Use of arguments

### ISSUE THREAD

**Issue by mtscout6** [kthompson55/Node-CLI-Intro#2]
In JavaScript when you use arguments like you are in your [`file`](https://github.com/kthompson55/Node-CLI-Intro/blob/master/src/CLI.js#L70) function there are some performance costs to doing so. See: http://bonsaiden.github.io/JavaScript-Garden/#function.arguments.

Since you are only taking one argument just declare that argument and all the noise to extract it become unnecessary. Although in the case that you do need them, use of the new spread semantics are preferred since that would show in  the function signature that more arguments can be supplied. See: http://babeljs.io/docs/learn-es6/#default-rest-spread

**Comment by kthompson55** [comment]
Since my implementation of writing the package.json file has changed, this issue is no longer relevant to the project.

Thanks for the information, though, mtscout6. I'll keep in it mind for future projects.
