### ISSUE TITLE
Use of Array.prototype.reduce()

### ISSUE THREAD

**Issue by mtscout6** [kthompson55/Node-CLI-Intro#3]
This pattern: https://github.com/kthompson55/Node-CLI-Intro/blob/master/src/CLI.js#L54-L56

Can be solved with [`Array.prototype.reduce()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)

**Comment by kthompson55** [comment]
The issue of combining the tags is no longer a desired goal, so I'm going to mark this as resolved.
