### ISSUE TITLE
Promise Chaining

### ISSUE THREAD

**Issue by mtscout6** [kthompson55/Node-CLI-Intro#4]
See my comments on Steve's repo: https://github.com/Stran6/ReleaseCLI/issues/6

**Comment by mtscout6** [comment]
Those same comments talk about string interpolation which you could use here: https://github.com/kthompson55/Node-CLI-Intro/blob/master/src/CLI.js#L82

**Comment by kthompson55** [comment]
Both chaining and string interpolation have been implemented. [git-handler](https://github.com/kthompson55/Node-CLI-Intro/blob/master/src/git-handler.js) has the most notable usage.

**Comment by mtscout6** [comment]
Looking a lot better!
